### ISSUE TITLE
Produces Angular Build Error "Unexpected token: punc ())"

### ISSUE THREAD

**Issue by Masterxilo** [techinity/url-parameter-append#10]
![image](https://user-images.githubusercontent.com/2378665/68292235-bb3cce80-008b-11ea-85bf-6fa279bb5ef0.png)
```

ERROR in main.1797730d0a22b456c51d.js from Terser
Unexpected token: punc ()) [./node_modules/url-parameter-append/url-parameter-append.js:20,0][main.1797730d0a22b456c51d.js:98924,4]
```

I built the project like this to finally find out that it was url-parameter-append.js that was causing the error:

`ng build --prod --named-chunks --verbose --build-optimizer=false --source-map
`
before that it only said

```
11:35:31  ERROR in main.c4408e442fefdd3760fb.js from Terser
11:35:31  Unexpected token: punc ()) [main.c4408e442fefdd3760fb.js:97835,4]
```

I fixed it by copying url-parameter-append.js to my code and removing the extra comma on line 19 so that it reads

```
      ...entries(args[0]).reduce((acc, item) => [...acc, ...item], [])
```

Please include this fix.

See also https://stackoverflow.com/a/58728706/524504

**Comment by allenevans** [comment]
Thanks for raising the issue.

I've refactored the project into typescript and release a new version https://github.com/techinity/url-parameter-append/releases.

Hopefully this will have solved your build issue caused by the projects linting settings. If not, please reopen this issue.
